DROP DATABASE IF EXISTS loyalty;
CREATE DATABASE loyalty;
USE loyalty;

CREATE TABLE Membership (
ID INT PRIMARY KEY AUTO_INCREMENT,
Number INT NOT NULL,
FirstName VARCHAR(25) NOT NULL,
LastName VARCHAR(25) NOT NULL,
Address VARCHAR(50) NOT NULL,
City VARCHAR(30) NOT NULL,
State VARCHAR(25) NOT NULL,
Zip VARCHAR(25) NOT NULL,
Telephone VARCHAR(10) NOT NULL,
Email VARCHAR(50) NULL,
Employee INT NOT NULL
);

CREATE TABLE Tranaction (
ID INT PRIMARY KEY AUTO_INCREMENT,
MembershipID INT NOT NULL,
Purchases VARCHAR(100) NOT NULL,
Date DATE NOT NULL,
FOREIGN KEY (MembershipID) References Membership (ID)
);